#!/usr/bin/env bash
# shellcheck disable=SC1091

#PBS -l select=1:ncpus=1:mem=100GB
#PBS -l walltime=4:00:00
#PBS -j oe
#PBS -P 12003580
#PBS -q normal

# load conda environment
module load miniconda3/py38_4.8.3
conda activate /home/users/ntu/suffiazi/apps/mambaforge/envs/plots

python3 /home/users/ntu/suffiazi/scripts/gatk-workflow-scripts/plotting/AF_FPS_site-counts-extraction.py /home/users/ntu/suffiazi/scratch/outputs/tmp/plotting-parallel/output-data /home/users/ntu/suffiazi/scratch/outputs/tmp/plotting-parallel/output-data/concat_tables


