#!/usr/bin/env bash
# shellcheck disable=SC1091

#PBS -l select=1:ncpus=12:mem=120GB
#PBS -l walltime=3:00:00
#PBS -j oe
#PBS -P 12003580
#PBS -q normal

# load conda environment
module load miniconda3/py38_4.8.3

conda activate /home/users/ntu/suffiazi/apps/mambaforge/envs/gatk-snv

# set up variables
tfbs_loc=$TF_FILE
bams=$BAM_INP
outfile=$OUT_DIR
motif_id=$TF_ID
data_id=$ID

# call and filter variants from bam files of BRCA datasets
bcftools mpileup -Ou -f /scratch/users/ntu/suffiazi/inputs/references/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta -T "${tfbs_loc}" -b "${bams}" | bcftools call -Ou -mv | bcftools filter -i'QUAL>10' > "${outfile}"/"${data_id}"_"${motif_id}"_qualgt10.var.flt.vcf