#!/usr/bin/env bash
# shellcheck disable=SC1091

#PBS -l select=1:ncpus=64:mem=150GB
#PBS -l walltime=20:00:00
#PBS -j oe
#PBS -P personal
#PBS -q normal

# load conda environment
module load miniconda3/py38_4.8.3
conda activate /home/users/ntu/suffiazi/apps/mambaforge/envs/gatk-snv

# set up variables
tfbs_loc=$TF_LIST
bams=$BAM_INP
outfile=$OUT_DIR
data_id=$ID

# read in TF motif list
readarray -t tfbs_beds < "$tfbs_loc"
echo "Number of TF motif bed files:" "${#tfbs_beds[@]}"

# loop through each TF motif
for bedfile in "${tfbs_beds[@]}"; do
    # run variant calling script in parallel using GNU parallel semaphore
    sem -j+0 pwd ";" echo bash /home/users/ntu/suffiazi/scripts/gatk-workflow-scripts/scripts/customs/run-bcftools_mpileup_module.sh "$bedfile" "$bams" "$outfile" "$data_id"
    echo "Running parallel job for $bedfile"
done
sem --wait