#!/usr/bin/env bash
# shellcheck disable=SC1091

#PBS -l select=1:ncpus=1:mem=80GB
#PBS -l walltime=5:00:00
#PBS -j oe
#PBS -P personal
#PBS -q normal

# check arguments
# if [ "$#" -ne 4 ]; then
#     echo "Usage: $0 <dataset_id_text_list> <motif_prefixes> <vcf_root_dir> <output_dir>"
#     exit 1
# fi

module load miniconda3/py38_4.8.3
conda activate /home/users/ntu/suffiazi/apps/mambaforge/envs/gatk-snv

# set up variables
data_id_list=$DATA
motif_prefixes=$MOTIFS
vcf_root_dir=$VCFS
output_dir=$OUT

# load dataset IDs
readarray -t data_ids < "$data_id_list"

# load motif prefixes from the input text file
mapfile -t motif_prefixes < "$motif_prefixes"

# process each dataset ID
for id in "${data_ids[@]}"; do
    echo "Dataset ID: $id"
    # loop through each motif prefix
    for motif_prefix in "${motif_prefixes[@]}"; do
        echo "Motif to process: $motif_prefix. Finding the file..."
        # find specific motif vcf file under this ID
        vcf_file=$(find "${vcf_root_dir}" -name "${id}_${motif_prefix}*.vcf" -type f)
        if [ -n "$vcf_file" ]; then
            echo "VCF file found: $vcf_file"
            # construct output filename
            mkdir -p "${output_dir}/${id}"
            output="${output_dir}/${id}/${id}_${motif_prefix}_AF-per-site"
            # check if output file already exists
            if [ ! -f "${output}".txt ]; then
                # extract the AF field from the vcf file
                if bcftools query -H -f '%CHROM\t%POS\t%REF\t%ALT\t%AF\n' --include 'TYPE="snp"' "${vcf_file}" > "${output}".txt; then
                    echo "Successfully extracted AF field from VCF file of ${motif_prefix} from ${id} dataset."
                else
                    echo "Failed to extract AF field from VCF file of ${motif_prefix} from ${id} dataset."
                fi
            else
                echo "Output file ${output}.txt already exists. Checking if the indel-included vcf matrix exists or not..."
                # construct output filename
                output_with_indel="${output_dir}/${id}/${id}_${motif_prefix}_AF-per-site-with-indels"
                # check if output file already exists
                if [ ! -f "${output_with_indel}".txt ]; then
                    # extract the AF field from the vcf file together with indels
                    if bcftools norm -m-both "${vcf_file}" | bcftools query -H -f '%CHROM\t%POS\t%REF\t%ALT\t%AF\n' - > "${output_with_indel}".txt; then
                        echo "Successfully extracted AF field from VCF file of ${motif_prefix} from ${id} dataset with indels included."
                    else
                        echo "Failed to extract AF field from VCF file of ${motif_prefix} from ${id} dataset with indels included."
                    fi
                else
                    echo "Output file ${output_with_indel}.txt already exists. Skipping..."
                    continue
                fi
            fi
        else
            echo "VCF file for ${motif_prefix} not found. Skipping..."
            continue
        fi
    done
done