#!/usr/bin/env bash
# shellcheck disable=SC1091

#PBS -l select=1:ncpus=4:mem=10GB
#PBS -l walltime=4:00:00
#PBS -j oe
#PBS -P personal
#PBS -q normal

# load conda environment
module load miniconda3/py38_4.8.3
conda activate /home/users/ntu/suffiazi/apps/mambaforge/envs/gatk-snv

# Function to calculate the Fibonacci sequence
fibonacci() {
    local n=$1
    if [ $n -le 1 ]; then
        echo $n
    else
        local a=0
        local b=1
        local result=0
        for ((i=2; i<=n; i++)); do
            result=$((a + b))
            a=$b
            b=$result
        done
        echo $result
    fi
}

# Calculate Fibonacci for a specific number

arr=(1 2 3 4 5 6 7 8 9 10)
for i in "${arr[@]}"; do
    fibonacci $i &
done
wait